  groupId: "basePackage" 
  artifactId: "artifactIdValue" 
  artifactVersion: "artifactVersionValue" 
  groupId: "basePackage.artifactIdValue" 
  basePackage: "basePackage.artifactIdValue" 
  apiPackage: "basePackage.artifactIdValue.api" 
  modelPackage: "basePackage.artifactIdValue.model" 
  configPackage: "basePackage.artifactIdValue.configuration" 
  invokerPackage: "basePackage.artifactIdValue.api" 
  title: "artifactIdValue"