  groupId: "basePackage" 
  artifactId: "artifactId" 
  artifactVersion: "artifactVersion" 
  groupId: "basePackage.artifactId" 
  basePackage: "basePackage.artifactId" 
  apiPackage: "basePackage.artifactId.api" 
  modelPackage: "basePackage.artifactId.model" 
  configPackage: "basePackage.artifactId.configuration" 
  invokerPackage: "basePackage.artifactId.api" 
  title: "artifactId"