  groupId: "basePackageValue" 
  artifactId: "artifactIdValue" 
  artifactVersion: "artifactVersionValue" 
  groupId: "basePackageValue.artifactIdValue" 
  basePackage: "basePackageValue.artifactIdValue" 
  apiPackage: "basePackageValue.artifactIdValue.api" 
  modelPackage: "basePackageValue.artifactIdValue.model" 
  configPackage: "basePackageValue.artifactIdValue.configuration" 
  invokerPackage: "basePackageValue.artifactIdValue.api" 
  title: "artifactIdValue"